### ISSUE TITLE
Move "Docker Environment Tutorials" from Resources to Week 1

### ISSUE THREAD

**Issue by nathan-duddles** [CIS548/docker-env#12]
In Coursera, we should move the [Docker Environment Tutorials](https://www.coursera.org/learn/cit595-2021c/resources/PR2R9) from Resources to immediately following [Project 0 Description](https://www.coursera.org/learn/cit595-2021c/supplement/fao0y/project-0-description) in Week 1.

**Comment by boonloo** [comment]
Yes this is a good change. In fact, the project 0 description should also reference the tutorials.

**Comment by nathan-duddles** [comment]
Yes, that is a good point! @kuang-da has already added the references in the new Docker version of Project 0: Description, so it would make sense that they follow right after.

**Comment by nathan-duddles** [comment]
Closing this issue, since Docker set up is now covered in the new [Project 0: Description](https://drive.google.com/drive/folders/1y7SCrD9vq6xr4Zt5AErX7zcuZP5NOmu-)
