### ISSUE TITLE
How to handle previously recorded Recitations for Project 0

### ISSUE THREAD

**Issue by nathan-duddles** [CIS548/docker-env#14]
Doing a search for "Vagrant" in Coursera brought up prior semesters' recorded Project 0 Recitations.

Would it make sense to remove previous Recitations? - To answer this later question, I would like to watch some of these videos and determine if they are still valuable in a post-Vagrant 595.

If we decide to keep them,  it might make sense to add a sentence to [Project 0 Description](https://github.com/CIS548/docker-env/issues/13)  to the effect that recorded Recitations for Project 0 from Fall 2021 are for a different Virtual Machine setup.

**Comment by boonloo** [comment]
If there's value to the previous ones besides Vagrant (i.e. if they provide some useful Linux commands), we should keep them with a note to use Docker.

**Comment by nathan-duddles** [comment]
It looks like we just have Fall 2021 Project 0 recitation in the Spring 2022 Coursera course. @kuang-da did a great job of presenting both Docker and Vagrant in this recitation and I think it is valuable to keep. He even mentions that future courses may be transitioning to Docker, so I don't think anyone will be confused by watching it. I'll also add some explanation of the transition in the new [Project 0 Description](https://docs.google.com/document/d/1Se_ncw_QvQluBo9k4gnIQqzWdACz8gHTIpG1zLlPaGk/edit#heading=h.j3iq48yowyh)

**Comment by kuang-da** [comment]
Sounds great. We usually did not have open office hours for project 0, and 2021 fall is the first attempt  : ) But it would be helpful to keep it happening!
