### ISSUE TITLE
Remove Vagrant-specific Coursera pages

### ISSUE THREAD

**Issue by nathan-duddles** [CIS548/docker-env#15]
Pages to be removed (or hidden from students):

In Week 1:
[Vagrant FAQs](https://www.coursera.org/learn/cit595-2021c/supplement/xZlG9/vagrant-faqs)

[TA Demo: Course VM Environment](https://www.coursera.org/learn/cit595-2021c/lecture/tXn1A)

In Resources:
[Project 0 VagrantFile](https://www.coursera.org/learn/cit595-2021c/resources/JpVgb)

Do we need to maintain a collection of Vagrant resources to be made available to any students for whom there is some insurmountable roadblock to using Docker, and form whom Vagrant may work? (Is that even likely?)

**Comment by boonloo** [comment]
I suggest we do a phased transition, where we make Vagrant and WSL the backup option and Docker the primary.

**Comment by nathan-duddles** [comment]
In this case, I propose we consolidate the above Vagrant set up materials to two pages that can be located in Coursera Resources section. If this sounds good, I can go ahead and move these in the Spring 2022 course.

_Alternate VM: Vagrant Instructions_

Containing content from:
[Current Project 0 Description](https://www.coursera.org/learn/cit595-2021c/supplement/fao0y/project-0-description)
[Project 0 VagrantFile](https://www.coursera.org/learn/cit595-2021c/resources/JpVgb)
[Vagrant FAQs](https://www.coursera.org/learn/cit595-2021c/supplement/xZlG9/vagrant-faqs)

_Alternate VM: Vagrant TA Demo_

Containing the video:
[TA Demo: Course VM Environment](https://www.coursera.org/learn/cit595-2021c/lecture/tXn1A)

**Comment by boonloo** [comment]
Sounds good.

**Comment by nathan-duddles** [comment]
Great! I will work on making these updates in Spring 2022 and comment when complete. I'm creating a new version of the Project 0 Description for Vagrant. [Saving in Google Docs here.](https://docs.google.com/document/d/1lg5zhhp8Xmv2zTepGsldrskQsNQggKKEQQ7zjeY_0tI/edit#)

**Comment by nathan-duddles** [comment]
I've updated the intro to the new version of [Project 0 Description for Vagrant](https://docs.google.com/document/d/1lg5zhhp8Xmv2zTepGsldrskQsNQggKKEQQ7zjeY_0tI/edit#) to direct students to first try using Docker. 

I've also consolidated Vagrant set up resources to [this page](https://www.coursera.org/learn/cit595-spring22/resources/JpVgb) in the Resources section.

I've removed the Vagrant FAQ page from the Week 1 content (those PDFs now available in the above page in Resources).

**Comment by nathan-duddles** [comment]
I've moved Project 0 TA demos that use Vagrant from Week 1 to [this page](https://www.coursera.org/learn/cit595-spring22/resources/giE2F) in the Resources section. I will record a new Demo that goes over these topics (VM creation, GitHub clone/push, and command line) using Docker and add it to Week 1.
