### ISSUE TITLE
Add python3

### ISSUE THREAD

**Issue by alesparza** [CIS548/docker-env#24]
Unless I'm reading `docker-setup.sh` wrong, we don't give the students python?  Can anyone confirm?

**Comment by kuang-da** [comment]
We did not explicitly install extra python in the current image. But Ubuntu 20.04 comes with Python3, isn't it? Is it good enough for the current projects?

**Comment by alesparza** [comment]
I guess that makes sense.  I'll follow up with the student to see if there are any more details.

**Comment by alesparza** [comment]
Student had to run `python3`.  The instructions are clear about that

**Comment by alesparza** [comment]
Student had to run `python3`.  The instructions are clear about that
