### ISSUE TITLE
Add automated test on Dockerfile

### ISSUE THREAD

**Issue by kuang-da** [CIS548/docker-env#3]

**Comment by angelapwen** [comment]
Should we also do this for the vagrant env? Or are we only going to do it for Docker considering we are planning to fully shift to Docker soon?

**Comment by kuang-da** [comment]
We should do it for vagrant env as well. But I believe the testing script can be generalized to both of them easily.

**Comment by kuang-da** [comment]
Made a PR for adding a test script #20.
