### ISSUE TITLE
Update Windows Instruction with PowerShell

### ISSUE THREAD

**Issue by kuang-da** [CIS548/docker-env#8]
Based on #7, we should make it more clear in the instruction to use the PowerShell launch Docker container, not WSL2. 

The [Windows instruction](https://docs.google.com/document/d/1D--4cVYUE3j7NXpZMSyEED_0OdSGfZyX/edit?usp=sharing&ouid=111931127109161708634&rtpof=true&sd=true) is here.

**Comment by nathan-duddles** [comment]
It's my bad for not seeing this issue earlier and incorporating it into the first draft of the [Project 0: Description](https://docs.google.com/document/d/1_dNvMT77o_yXyFkbBABtKSudNsGoUAc4nDapeQv10fI/edit#heading=h.j3iq48yowyh) instructions for Docker Setup. It is now added as an 'Important Note' on the second page.
